# This file is meant to describle the Honda Insight (1999) in a .toml format. 

car_model_type = "dynamic"
powertrain_type = "electric"

[general]
    lf = 0.960  # weight distribution: 60/40 f/r https://www.motortrend.com/reviews/2000-honda-insight-2/
    lr = 1.440  # wheelbase: 2400mm  https://www.autoevolution.com/cars/honda-insight-1999.html#aeng_honda-insight-1999-10
    h_cog = 0.4  # (estimated) height of 0.5m for e30 CoG https://www.steerbythrottle.com/hccyong/cars/susp_analysis.htm
    sf = 1.435 # https://www.autoevolution.com/cars/honda-insight-1999.html#aeng_honda-insight-1999-10
    sr = 1.326 # https://www.autoevolution.com/cars/honda-insight-1999.html#aeng_honda-insight-1999-10
    # m = 850.0 # https://en.wikipedia.org/wiki/Honda_Insight
    # f_roll = 0.02 # determined by mass and rolling resistance factor
    # c_w_a = 0.475  # 1.90 meters squared * 0.25 drag coeff https://www.curbsideclassic.com/automotive-histories/automotive-aerodynamics-drag-area-size-matters/
    c_z_a_f = 0.0 # assume no aero
    c_z_a_r = 0.0 # assume no aero
    g = 9.81
    rho_air = 0.84 # at 1 mile high for High Plains Raceway
    drs_factor = 0.0
    coefficient_of_drag = 0.38  # unitless
    vehicle_curb_mass = 852  # kg
    mass_reduction = 180  # kg
    chassis_motor_mass_factor = 0.05 # kg chassis per kg motor
    chassis_battery_mass_factor = 0.05 # kg chassis per kg battery
    car_density = 450 # kg/m^3
    max_vehicle_weight_ratio = 1.25  # determined by rules
    rolling_resistance_mass_factor = 0.00001 #0.01 rolling resistance for 1000 kg car
[battery]
    size = [10.0, 100.0, 10.0]  # kWh # kWh
    energy_density = 0.15  # kWh/kg
    change_constant = 3  # minutes
    mass_pit_factor = 0.03  # minutes per kg of battery of pit time
    power_output_factor = 3500 # Watts output per kWh battery capacity
[engine]
    topology = "FWD"
    # pow_e_motor = 130e3  # 200 hp (149kw) measured at wheels (maximum) derated some b/c we don't get max power the whole time
    # 130e3  # 200 hp (149kw) measured at wheels (maximum) derated some b/c we don't get max power the whole time
    eta_e_motor = 1 # measured torque + horse power at wheels so all efficiencies are accounted for
    eta_e_motor_re = 1 # measured torque + horse power at wheels so all efficiencies are accounted for
    # torque_e_motor_max = 100.0  # new variable name
    motor_max_torque = 240.0 # ~200 ft*lb's (270 Nm) measured at the wheel (maximum) derated some b/c we don't get max torque the whole time
    motor_constant = 0.79  # Nm/sqrt(W)
    motor_torque_density = 5.6 # Nm/kg
[gearbox]
    i_trans = [0.0701, 0.1219, 0.1915, 0.2681, 0.3309]  # getrag 265 + 3.73lsd (aftermarket) https://people.physics.anu.edu.au/~amh110/gearbox_ratios_compared.htm
    n_shift = [5500.0, 5500.0, 5500.0, 5500.0, 5500.0] # type of transmission: https://en.wikipedia.org/wiki/BMW_5_Series_(E28)#Drivetrain
    e_i = [1.04, 1.04, 1.04, 1.04, 1.04]
    eta_g = 1.0 # measured torque + horse power at wheels so all efficiencies are accounted for
[tires]
    tire_model_exp = 2.0
    [tires.f]
        circ_ref = 1.791 # Insight: 165-65R14 https://www.1010tires.com/Tools/Tire-Size-Calculator
        fz_0 = 1667.1  # # weight of car 850*9.80665 * 0.40 / 2 assume nominal tire load is weight on tires when still
        mux = 1.02 # 200 tread wear tire + equation here: https://en.wikipedia.org/wiki/Uniform_Tire_Quality_Grading
        muy = 1.02 # 200 tread wear tire + equation here: https://en.wikipedia.org/wiki/Uniform_Tire_Quality_Grading
        dmux_dfz = -2.5e-5
        dmuy_dfz = -2.5e-5
    [tires.r]
        circ_ref = 1.791 # Insight: 165-65R14 https://www.1010tires.com/Tools/Tire-Size-Calculator
        fz_0 = 1667.1  # # weight of car 850*9.80665 * 0.40 / 2 assume nominal tire load is weight on tires when still
        mux = 1.02 # 200 tread wear tire + equation here: https://en.wikipedia.org/wiki/Uniform_Tire_Quality_Grading
        muy = 1.02 # 200 tread wear tire + equation here: https://en.wikipedia.org/wiki/Uniform_Tire_Quality_Grading
        dmux_dfz = -2.0e-5
        dmuy_dfz = -2.0e-5