# This file is meant to describle the BMW e28 (528e) in a .toml format. 

car_model_type = "dynamic"
powertrain_type = "electric"

[general]
    lf = 0.918 # weight distribution: 65/35 f/r https://www.mye28.com/viewtopic.php?t=154907
    lr = 1.706 # wheelbase: 2625mm https://www.carinf.com/en/5990423541.html
    h_cog = 0.5 # height of e30 CoG https://www.steerbythrottle.com/hccyong/cars/susp_analysis.htm
    sf = 1.431 # https://www.carinf.com/en/5990423541.html
    sr = 1.471 # https://www.carinf.com/en/5990423541.html
    # m = 3000.0  # determined by other variables
    # f_roll = 0.02 # determined by mass and rolling resistance factor
    # c_w_a = 0.802  # 2.01 meters squared * 0.4 drag coeff
    c_z_a_f = 0.0
    c_z_a_r = 0.0
    g = 9.81
    rho_air = 0.84 # at 1 mile high
    drs_factor = 0.0
    coefficient_of_drag = 0.38  # unitless
    vehicle_curb_mass = 1225  # kg # https://en.wikipedia.org/wiki/BMW_5_Series_(E28)#Suspension (estimated)
    mass_reduction = 180  # kg
    chassis_motor_mass_factor = 0.05 # kg chassis per kg motor
    chassis_battery_mass_factor = 0.05 # kg chassis per kg battery
    car_density = 450 # kg/m^3
    max_vehicle_weight_ratio = 1.25  # determined by rules
    rolling_resistance_mass_factor = 0.00001 #0.01 rolling resistance for 1000 kg car
[battery]
    size = [10.0, 100.0, 10.0]  # kWh # kWh
    energy_density = 0.15  # kWh/kg
    change_constant = 3  # minutes
    mass_pit_factor = 0.03  # minutes per kg of battery of pit time
    power_output_factor = 3500 # Watts output per kWh battery capacity
[engine]
    topology = "RWD"
    # pow_e_motor = 130e3  # determined by motor constant and torque
    # 130e3  # 200 hp (149kw) measured at wheels (maximum) derated some b/c we don't get max power the whole time
    eta_e_motor = 1.0
    eta_e_motor_re = 1.0
    # torque_e_motor_max = 100.0  # new variable name
    motor_max_torque = 275.0  # Nm
    motor_constant = 0.79  # Nm/sqrt(W)
    motor_torque_density = 5.6 # Nm/kg
[gearbox]
    i_trans = [0.0701, 0.1219, 0.1915, 0.2681, 0.3309]  # getrag 265 + 3.73lsd (aftermarket) https://people.physics.anu.edu.au/~amh110/gearbox_ratios_compared.htm
    n_shift = [5500.0, 5500.0, 5500.0, 5500.0, 5500.0] # type of transmission: https://en.wikipedia.org/wiki/BMW_5_Series_(E28)#Drivetrain
    e_i = [1.04, 1.04, 1.04, 1.04, 1.04]
    eta_g = 1
[tires]
    tire_model_exp = 2.0
    [tires.f]
        circ_ref = 1.974 # http://www.scrappycrow.com/e28wheelstires/e28wheelstires.html
        fz_0 = 3905.0  # weight of car * 0.65 / 2 assume nominal tire load is weight on tires when still
        mux = 1.02 # 200 tread wear tire + equation here: https://en.wikipedia.org/wiki/Uniform_Tire_Quality_Grading
        muy = 1.02 # 200 tread wear tire + equation here: https://en.wikipedia.org/wiki/Uniform_Tire_Quality_Grading
        dmux_dfz = -2.5e-5
        dmuy_dfz = -2.5e-5
    [tires.r]
        circ_ref = 1.974 # http://www.scrappycrow.com/e28wheelstires/e28wheelstires.html
        fz_0 = 2103.0  # # weight of car * 0.35 / 2 assume nominal tire load is weight on tires when still
        mux = 1.02 # 200 tread wear tire + equation here: https://en.wikipedia.org/wiki/Uniform_Tire_Quality_Grading
        muy = 1.02 # 200 tread wear tire + equation here: https://en.wikipedia.org/wiki/Uniform_Tire_Quality_Grading
        dmux_dfz = -2.0e-5
        dmuy_dfz = -2.0e-5