# This .toml file is a copy of the oritinal FE_Berlin.ini original TUM car file

car_model_type = "dynamic"
powertrain_type = "electric"

[general]
    lf = 1.906
    lr = 1.194
    h_cog = 0.345
    sf = 1.3
    sr = 1.3
    # m = 3000.0  # determined by other variables
    # f_roll = 0.02 # determined by mass and rolling resistance factor
    # c_w_a = 1.15  # determined by frontal area and coefficient of drag
    c_z_a_f = 0.1
    c_z_a_r = 0.1
    g = 9.81
    rho_air = 1.18
    drs_factor = 0.0
    coefficient_of_drag = 0.3  # unitless
    vehicle_curb_mass = 1200  # kg
    mass_reduction = 200  # kg
    chassis_motor_mass_factor = 0.05 # kg chassis per kg motor
    chassis_battery_mass_factor = 0.05 # kg chassis per kg battery
    car_density = 100 # kg/m^3
    max_vehicle_weight_ratio = 1.25  # determined by rules
    rolling_resistance_mass_factor = 0.00001 #0.01 rolling resistance for 1000 kg car
[battery]
    size = [10.0, 100.0, 10.0]  # kWh
    energy_density = 0.5  # kWh/kg
    change_constant = 3  # minutes
    mass_pit_factor = 0.03  # minutes per kg of battery of pit time
    power_output_factor = 1000 # Watts output per kWh battery capacity
[engine]
    topology = "RWD"
    # pow_e_motor = 100e3  # determined by motor constant and torque
    eta_e_motor = 0.9
    eta_e_motor_re = 0.9
    # torque_e_motor_max = 100.0  # new variable name
    motor_max_torque = [100.0, 300.0, 3.0]  # Nm
    motor_constant = 0.9  # Nm/sqrt(W)
    motor_torque_density = 5 # Nm/kg
[gearbox]
    i_trans = [0.056, 0.091]
    n_shift = [19000.0, 19000.0]
    e_i = [1.04, 1.04]
    eta_g = 0.96
[tires]
    tire_model_exp = 2.0
    [tires.f]
        circ_ref = 2.168
        fz_0 = 2500.0
        mux = 1.22
        muy = 1.22
        dmux_dfz = -2.5e-5
        dmuy_dfz = -2.5e-5
    [tires.r]
        circ_ref = 2.168
        fz_0 = 2500.0
        mux = 1.42
        muy = 1.42
        dmux_dfz = -2.0e-5
        dmuy_dfz = -2.0e-5
